name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
      - name: Run Feed Generator
        uses: geckoboom/podcast-generator@main
        with:
          email: ${{ github.actor }}@localhost
          name: ${{ github.actor }}
